name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust
        run: |
          rustup install stable
          rustup default stable
      
      - name: Build Windows App
        working-directory: ./windows
        run: cargo build --release
      
      - name: Find and Show EXE file
        run: |
          echo "Searching for .exe files in the 'windows' folder..."
          Get-ChildItem -Path .\windows -Recurse -Filter *.exe | Select-Object FullName, Name, Length
      
      - name: Upload the EXE file
        uses: actions/upload-artifact@v4
        with:
          name: iranvpn-exe-file
          path: .\windows\target\release\*.exe
      - name: Upload whole windows folder (just in case)
        uses: actions/upload-artifact@v4
        with:
          name: whole-windows-folder
          path: .\windows
