name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Rust
        run: |
          rustup install stable
          rustup default stable
      
      - name: Build Windows App (Release)
        working-directory: ./windows
        run: cargo build --release
      
      - name: Get version
        id: version
        run: |
          echo "date=$(date '+%Y.%m.%d')" >> $env:GITHUB_OUTPUT
      
      - name: Create Release and Upload exe
        uses: softprops/action-gh-release@v2
        with:
          tag_name: windows-build-${{ steps.version.outputs.date }}
          name: Windows Build - ${{ steps.version.outputs.date }}
          body: |
            فایل اجرایی ویندوز - تاریخ ساخت ${{ steps.version.outputs.date }}
            
            **نحوه استفاده:**
            فایل iranvpn.exe را دانلود و اجرا کنید.
          files: ./windows/target/release/*.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
